### ISSUE TITLE
Add support for bs-platform@5

### ISSUE THREAD

**Issue by dteoh** [ostera/bsdoc#10]
It would be great to have support for the current stable release of bs-platform :)

EDIT: I did manage to `esy build` something that uses `"ocaml": "4.2.3007"` + changing a bunch of other deps to use `*` as the version + adding a helper for `Hashtbl.find_opt`, but I don't really know how to proceed with using these local changes in a different project.

**Comment by leostera** [comment]
Could you submit a PR with those changes? If we get it merged we can publish `bsdoc@5` to use with `bs-platform@5`

**Comment by yawaramin** [comment]
Now working with bs-platform 6+
