### ISSUE TITLE
Use odoc API calls to compile .odoc and .html files instead of shelling out to odoc binary

### ISSUE THREAD

**Issue by yawaramin** [ostera/bsdoc#18]
It should be possible to call the odoc API directly instead of shelling out twice for every file in the project.

**Comment by yawaramin** [comment]
- Compile to .odoc: https://github.com/ocaml/odoc/blob/1.4.1/src/odoc/compile.mli
  - Env builder: https://github.com/ocaml/odoc/blob/1.4.1/src/odoc/env.mli
  - Package is just a string
- Compile .odoc to HTML: https://github.com/ocaml/odoc/blob/1.4.1/src/odoc/html_page.mli
  - Syntax: https://github.com/ocaml/odoc/blob/1.4.1/src/html/tree.mli
  - output: docs/ dir

**Comment by jonludlam** [comment]
This may not be a good idea, particularly with the new model. It's quite aggressive with caching and memoizing for performance - though it does depend on which libraries you're using.

**Comment by yawaramin** [comment]
@jonludlam yeah, now I'm leaning more towards using BuckleScript's vendored Ninja build tool to drive doc generation using just odoc compile and odoc html calls.

**Comment by jonludlam** [comment]
sounds good. Out of interest, does ninja need to know what files will be produced? (ie, the html-targets command)

**Comment by yawaramin** [comment]
Yeah, at least roughly the main outputs. For example, and I'm planning to implement this, if I have a file `src/foo/foo__bar.ml`, then I need to tell Ninja about the following outputs from `odoc html`:

- `docs/foo__bar/index.html`
- `docs/foo/bar/index.html` (because of alias `module Bar = Foo__Bar` in `src/foo.ml`)

**Comment by yawaramin** [comment]
@jonludlam oh, I just realized `odoc html-targets` is an actual command, which, I assume, prints out the output HTML files. Will look into that.

**Comment by jonludlam** [comment]
I wouldn't rely on it in its current implementation, but think of it as an aspirational command - we'll get it right next version :-)

**Comment by yawaramin** [comment]
Closing to try Ninja-driven approach as mentioned above.
