### ISSUE TITLE
Random Symbols in output

### ISSUE THREAD

**Issue by piq9117** [ostera/bsdoc#4]
Hey @ostera thanks for this project! 

I remember this being discussed in discord but I can't find the history so I'm here filing this issue. This is the output I get

<img width="793" alt="screen shot 2019-01-12 at 5 53 30 pm" src="https://user-images.githubusercontent.com/12651509/51090230-58fe9000-173e-11e9-8a44-22a912d23027.png">

**Comment by leostera** [comment]
Hello @piq9117! Sorry for the delay. 

BuckleScript encodes internal data in the values of `external`. The latest master from `odoc` has a patch that hides this so you will see `let apiKey : mailgunReq => string;` instead :)

I'll update `bsdoc` as soon as an `odoc` release happens.

**Comment by piq9117** [comment]
no worries! thanks for responding. I'll checkout `odoc` for now.
